from groq import Groq
from config import GROQ_API_KEY

client = Groq(api_key=GROQ_API_KEY)

def detect_ai(text):
    prompt = f"""
You are an AI provenance detector.

Read the following text and estimate the probability that it was generated by AI.

Return ONLY a decimal number between 0 and 1.

Text:
{text}
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "user", "content": prompt}
        ],
        temperature=0
    )

    result = response.choices[0].message.content.strip()

    try:
        return float(result)
    except:
        return 0.5