def generate_label(attribution: str, confidence: float) -> str:
    pct = round(confidence * 100)

    if attribution == "likely_ai":
        return (
            f"Likely AI Generated\n"
            f"Confidence: {pct}%\n"
            f"Our analysis found strong indicators commonly associated with AI-generated writing. "
            f"This result is probabilistic and should not be treated as definitive proof."
        )
    elif attribution == "likely_human":
        return (
            f"Likely Human Written\n"
            f"Confidence: {pct}%\n"
            f"Our analysis found stronger evidence of human writing patterns than AI-generated patterns. "
            f"This result is probabilistic and not a guarantee."
        )
    else:
        return (
            f"Uncertain\n"
            f"Confidence: {pct}%\n"
            f"The available evidence is mixed. The system cannot confidently determine whether "
            f"this content was written by a human or generated by AI."
        )